### ISSUE TITLE
Mod crashes upon startup 

### ISSUE THREAD

**Issue by JanCantCode** [0x3C50/Renderer#34]
# Bug Description
When trying to gradlew runClient whilst having renderer as a dependency, the mod crashes with
```java.lang.AbstractMethodError: Receiver class net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator$2 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.resource.ResourcePack open(java.lang.String)' of interface net.minecraft.resource.ResourcePackProfile$PackFactory.
	at net.minecraft.resource.ResourcePackProfile.loadMetadata(ResourcePackProfile.java:70)
	at net.minecraft.resource.ResourcePackProfile.create(ResourcePackProfile.java:47)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.register(ModResourcePackCreator.java:84)
	at net.minecraft.client.option.GameOptions.handler$zeh000$fabric-resource-loader-v0$onLoad(GameOptions.java:2368)
	at net.minecraft.client.option.GameOptions.load(GameOptions.java:1480)
	at net.minecraft.client.option.GameOptions.<init>(GameOptions.java:1237)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:460)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

i am not using any resourcepacks in my dev enviroment, and removing the dependency fixes it. 

# Expected Behavior
The game starting up as expected and not crashing

# Desktop
 - OS: Windows
- GPU: Nvidia

# Additional Context
Before i managed to get this error, i got a different error, fabric trying to parse "minecraft" as a version string from some fabric.mod.json, removing Renderer as a dependency fixed that issue but after readding it, i am getting the above described error.

Any idea whats going on here?

**Comment by JanCantCode** [comment]
turns out it isnt an issue on the end of renderer but rather just gradle not fully applying mappings and  therefore stuff breaking..
