### ISSUE TITLE
Version control?

### ISSUE THREAD

**Issue by Puiching-Memory** [0x3C50/Renderer#39]
after i use
`include modImplementation("com.github.0x3C50:Renderer:master-SNAPSHOT")`

Such an error has occurred

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.IllegalStateException: duplicate fabric loader classes found on classpath: jar:file:/C:/Users/11386/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.15.7/809a1a6b0f4bcca07e3dffc01f8a62265db3ff5d/fabric-loader-0.15.7.jar!/net/fabricmc/loader/api/FabricLoader.class, jar:file:/C:/Users/11386/.gradle/caches/modules-2/files-2.1/net.fabricmc/fabric-loader/0.15.6/2b6b8b0f6d842b6891f7c9b8b66f2aed12bc2619/fabric-loader-0.15.6.jar!/net/fabricmc/loader/api/FabricLoader.class
        at net.fabricmc.loader.impl.util.LoaderUtil.verifyClasspath(LoaderUtil.java:65)
        at net.fabricmc.loader.impl.launch.knot.Knot.<clinit>(Knot.java:347)
        ... 2 more
```

Just changing the fabric-api version of my project is not enough, because the project also bundles other things, such as satin version 1.16, which is only available on 1.20.4, while my development version is 1.20.1

**Comment by 0x3C50** [comment]
use `gradle dependencies` to view the dependency tree. this is very likely not caused by my mod. if you want to change a version of a dependency, use `exclude` in the `modImplementation` configuration

**Comment by Puiching-Memory** [comment]
Thank you for your answer
I upgraded the Frabic of my project from 0.15.6 to 0.15.7 to temporarily resolve this issue
At this point I could go further, but frabic terminates the process, prompting that satin=1.16.0 requires MC above 1.20.3

My configuration in the `build.gradle` file is as follows：
```
	include modImplementation ("org.ladysnake:satin:${satin_version}")
	include modImplementation("com.github.0x3C50:Renderer:master-SNAPSHOT")
```

Here the value of satin_version is 1.14.0, declared in gradle.properties
Even so gradle ignored my Settings and chose version 1.16, which happened after the Renderer was added.
is there any way to lock the satin version?

**Comment by Puiching-Memory** [comment]
Based on the method you provided, I see that the satin dependency is 1.16, which overrides the 1.14 I set
```
+--- com.github.0x3C50:Renderer:master-SNAPSHOT
|    +--- org.apache.xmlgraphics:batik-transcoder:1.17
|    |    +--- org.apache.xmlgraphics:batik-anim:1.17
|    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-util:1.17
|    |    |    |    |    +--- org.apache.xmlgraphics:batik-constants:1.17
|    |    |    |    |    |    \--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    |    +--- org.apache.xmlgraphics:batik-i18n:1.17
|    |    |    |    |    |    \--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    |    \--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    \--- org.apache.xmlgraphics:xmlgraphics-commons:2.9
|    |    |    |         +--- commons-io:commons-io:2.11.0
|    |    |    |         \--- commons-logging:commons-logging:1.0.4
|    |    |    +--- org.apache.xmlgraphics:batik-css:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:xmlgraphics-commons:2.9 (*)
|    |    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    |    +--- org.apache.xmlgraphics:batik-dom:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-css:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-ext:1.17
|    |    |    |    |    \--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-xml:1.17
|    |    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    |    \--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    |    +--- xml-apis:xml-apis:1.4.01
|    |    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    |    +--- org.apache.xmlgraphics:batik-ext:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-parser:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-xml:1.17 (*)
|    |    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    +--- org.apache.xmlgraphics:batik-svg-dom:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-css:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-dom:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-ext:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-parser:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-bridge:1.17
|    |    |    +--- org.apache.xmlgraphics:batik-anim:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-css:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-dom:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-gvt:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    \--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-parser:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-script:1.17
|    |    |    |    +--- org.apache.xmlgraphics:batik-anim:1.17 (*)
|    |    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    |    \--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    +--- org.apache.xmlgraphics:batik-svg-dom:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-xml:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:xmlgraphics-commons:2.9 (*)
|    |    |    \--- xml-apis:xml-apis-ext:1.3.04
|    |    +--- org.apache.xmlgraphics:batik-dom:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-gvt:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    +--- org.apache.xmlgraphics:batik-svggen:1.17
|    |    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    |    \--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-xml:1.17 (*)
|    |    \--- xml-apis:xml-apis-ext:1.3.04
|    +--- org.apache.xmlgraphics:batik-codec:1.17
|    |    +--- org.apache.xmlgraphics:batik-awt-util:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-bridge:1.17 (*)
|    |    +--- org.apache.xmlgraphics:batik-shared-resources:1.17
|    |    +--- org.apache.xmlgraphics:batik-transcoder:1.17 (*)
|    |    \--- org.apache.xmlgraphics:batik-util:1.17 (*)
|    +--- de.javagl:obj:0.4.0
|    +--- net.fabricmc.fabric-api:fabric-api:0.96.4+1.20.4 (*)
|    +--- org.ladysnake:satin:1.16.0
|    |    +--- net.fabricmc:fabric-loader:0.15.3 -> 0.15.7
|    |    \--- net.fabricmc.fabric-api:fabric-api:0.91.3+1.20.4 -> 0.96.4+1.20.4 (*)
|    \--- net.fabricmc:fabric-loader:0.15.7
\--- org.ladysnake:satin:1.14.0 -> 1.16.0 (*)
```

**Comment by Puiching-Memory** [comment]
我使用了以下方法锁定了版本，涉及satin和fabric-loader
```
configurations.all{
    resolutionStrategy{
        force ("org.ladysnake:satin:${satin_version}")
		force ("com.mojang:minecraft:${project.minecraft_version}")
		force ("net.fabricmc:yarn:${project.yarn_mappings}:v2")
		force ("net.fabricmc:fabric-loader:${project.loader_version}")
		force ("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")
    }
}
```
Now I can launch the game successfully
